version: '3'
services:

  data-obfuscate:
    image: zelig-data-obfuscate:1.0.0-SNAPSHOT
    container_name: "data-obf-transformer"
    network_mode: host
    restart: on-failure
    environment:
    - bootstrap.servers=localhost:9092
    - kafka.broker=localhost:9092    
    - zookeeper.connect=localhost:2181

#registry.dev.redbee.io/
